version: '3.4'

services:
  contentdistributionapp:
    image: contentdistributionapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      
  redis:
    image: redis